### ISSUE TITLE
CUBLAS Allocation

### ISSUE THREAD

**Issue by KevinWilliamHoffman** [bklynhlth/openwillis#41]
Hello,

I have been running the Facial Expressivity Code successfully, but have had difficulty with the Emotional Expressivity function.

import openwillis as ow
import pandas as pd
filename = "testvideo"
openwillisdir = "/data/home10/fani_share/OpenWillis/"
outputdir = openwillisdir + "Processed/" + filename + "/"
**framewise, summary = ow.emotional_expressivity(filepath = '/data/home10/fani_share/OpenWillis/Videos/testvideo/testvideomp4.mp4')**
framewise.to_csv(outputdir + filename + "_ee_framewise.csv")
ee_summary.to_csv(outputdir + filename + "_ee_summary.csv")
print("done")

Above is the code I have been running. I have bolded the line for most recent call traceback.

This is the error that comes up:
tensorflow/stream_executor/cuda/cuda_blas.cc:232] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED

I am wondering if you could help resolve this error. It may be a memory issue based on what I have seen online, but the node I am running in should not have a memory shortage. Additionally, the traceback being on the function line, it may be due to just improper notation I have not found how to fix yet.

I greatly appreciate your assistance!

**Comment by vjbytes102** [comment]
@KevinWilliamHoffman 

It seems like a memory allocation issue on your machine: TensorFlow's CUDA backend is having trouble allocating memory for the cuBLAS.

Are you on a gpu machine? if so, try cpu (easy fix).

**Comment by KevinWilliamHoffman** [comment]
Greetings,

I was able to resolve the issue using the bolded lines of code. However, I now have another difficulty.

import openwillis as ow
import pandas as pd
**import tensorflow as tf
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)**

filename = "testvideo"
openwillisdir = "/data/home10/fani_share/OpenWillis/"
outputdir = openwillisdir + "Processed/" + filename + "/"
framewise, summary = ow.emotional_expressivity(filepath = '/data/home10/fani_share/OpenWillis/Videos/testvideo/testvideomp4.mp4')

framewise.to_csv(outputdir + filename + "_ee_framewise.csv")
summary.to_csv(outputdir + filename + "_ee_summary.csv")
print("done")

In the past before the CubLAS error, I would run this function and obtain an Excel file correctly. I completed dozens of participant data before I began looking inside the files and found them empty except for the headings. It seems to be producing the headings and frames correctly, but not actually including the data in the excel file using the code above.

I have been able to use the Facial Expressivity function correctly and obtain data correctly using very similar code, but the Emotional Expressivity function still is not working for me. Could you help troubleshoot this in the context of my code above?

I greatly appreciate your assistance so far.

**Comment by KevinWilliamHoffman** [comment]
For more context, when I print(summary) I obtain the Not A Number error. I have checked and confirmed the quality of the video file I am using and have tried both .mov and .mp4

Here is the dataframe that prints for summary

angry  disgust  fear  happiness  sadness  surprise  neutral  composite
mean    NaN      NaN   NaN        NaN      NaN       NaN      NaN        NaN
std     NaN      NaN   NaN        NaN      NaN       NaN      NaN        NaN

**Comment by anzarabbas** [comment]
@vjbytes102 @KevinWilliamHoffman did we resolve this issue? If so, post result and let's close this out.

**Comment by KevinHoffman1** [comment]
I resolved this issue using the below code

config = tf.compat.v1.ConfigProto(gpu_options = tf.compat.v1.GPUOptions(per_process_gpu_memory_fraction=0.8)
#device_count = {'GPU': 1}
)
config.gpu_options.allow_growth = True
session = tf.compat.v1.Session(config=config)
tf.compat.v1.keras.backend.set_session(session)

It seems it was a memory allocation issue on the operating system. Allowing growth of the GPU allowed the framewise Emotional Expressivity to continue and then the Emotional Expressivity Summary to be calculated without producing the NaN outputs.
